export default function Skills() {
  return (
    <div>
      <img
        align="left"
        height="400"
        width="400"
        alt="GIF"
        src="https://firebasestorage.googleapis.com/v0/b/portfolio-5712a.appspot.com/o/Picture1.png?alt=media&token=0958ee42-545a-40a5-837c-bd5e51700221"
      />
      <br />
      <h2 style={{ color: "white" }}>**SKILLS I KNOW:**</h2>
      <br />
      <br />
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/C/C-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/C/C++-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/C/C-Sharp-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/P/PHP-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/J/Java-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/H/HTML-5-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/J/JavaScript-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/icon-download/P/Python-icon-vector-04.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/C/CSS-3-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/H/HTML-5-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/1024px-Git_icon.svg.png"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/github-api/github-api.png"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://cdn.worldvectorlogo.com/logos/nodejs-icon.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/R/React-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/M/MySQL-logo-vector-01.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1PKsfJXnxOqnTRiIZ8VcdJDYBXD-qZnnpw&usqp=CAU"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://brandeps.com/logo-download/A/Android-logo-vector-02.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="40"
          src="https://upload.wikimedia.org/wikipedia/commons/a/ab/Linux_Logo_in_Linux_Libertine_Font.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="30"
          src="https://brandeps.com/icon-download/V/Visual-studio-code-icon-vector-02.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="30"
          src="https://brandeps.com/icon-download/V/Visual-studio-icon-vector-02.svg"
        />
      </code>
      <code>
        <img
          height="40"
          width="30"
          src="https://brandeps.com/icon-download/U/Unity-icon-vector-01.svg"
        />
      </code>
    </div>
  );
}
